name: "🚨 Security Vulnerability"
description: Report a suspected or confirmed vulnerability that could be exploited
labels: ["security", "critical", "needs-investigation"]
body:
  - type: markdown
    attributes:
      value: |
        🚨 **STOP! BEFORE SUBMITTING:**  
        If this vulnerability could expose sensitive data or affect users in a serious way,  
        please also contact us privately at: **security@yourproject.com**

        This form is for reporting actual or suspected vulnerabilities.

  - type: textarea
    id: vulnerability_description
    attributes:
      label: Description of Vulnerability
      description: Why this is a vulnerability and its potential impact
      placeholder: "This endpoint allows unauthenticated access to user data."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact & Exploitability
      placeholder: |
        Examples:
        - Privilege escalation
        - Data access without authentication
        - Remote code execution
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Step-by-step way to reproduce the issue
      placeholder: |
        1. Visit /admin/settings
        2. Intercept request and modify token...
        3. Access granted without auth
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept (No Live Data)
      description: Anonymised payloads, redacted logs, or minimal example code
      placeholder: "curl -X POST https://example.com/api ..."

  - type: input
    id: affected_versions
    attributes:
      label: Affected Versions / Environments
      placeholder: "v1.3.0 / iOS / Chrome / Windows"
      description: Include OS/platform if relevant.

  - type: textarea
    id: recommendations
    attributes:
      label: Suggested Fix (Optional)
      placeholder: "Validate authorization token before processing request."

  - type: textarea
    id: notes
    attributes:
      label: Additional Info
      placeholder: "Any extra context or edge cases."
